services:
  api:
    build:
      context: ./movie_api
    container_name: movie_api
    ports:
      - "5000:5000"
    restart: unless-stopped

  front:
    build:
      context: ./movie_front
    container_name: movie_front
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - api
